version: '3.4'

services:
  hw2-rentacar.api:
    image: ${DOCKER_REGISTRY-}hw2rentacarapi
    build:
      context: .
      dockerfile: HW2-RentACar.API/Dockerfile
    ports:
      - "1450:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Abc1234567"
        ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
